[feat] authentication and authorization
hammer-hfut/rehearsal-room-management-backend pull request #7
Opened 2024-02-14 08:00 UTC by Prixii

👍 #2 
- [x] 登录接口
- [x] 通用认证与鉴权功能（注解与过滤器）
- [x] 角色管理相关接口

2024-02-18 07:25 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/AuthInterceptor.kt
> +const val DEBUG_MODE = false
把DEBUG_MODE从这里的硬编码改为从application.yml或.env里读取

2024-02-18 07:27 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/AuthInterceptor.kt
> +    override fun filter(p0: ContainerRequestContext?) {
1. 参数命名用 `context` 一类的有意义的词
2. 参数类型带问号是因为接口定义于 Java，看一下接口对应方法的文档注释，如果能确定此处不为 `null`，去掉问号

2024-02-18 07:28 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/AuthInterceptor.kt
> +const val LOGIN_API_PATH = "/auth/login"
`LOGIN_API_PATH` 同上，可以设置默认值

2024-02-18 07:30 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/AuthInterceptor.kt
> +        val badResponse = BusinessError(ErrorCode.UNAUTHORIZED)
设置可见权限

2024-02-18 07:31 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/AuthInterceptor.kt
> +const val LOGIN_API_PATH = "/auth/login"
把 `DEBUG_MODE` 和 `LOGIN_API_PATH` 从这里的硬编码改为从 `application.yml` 或 `.env` 里读取，可以设置默认值

2024-02-18 07:34 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/RolesRequired.kt
> +annotation class RolesRequired (val rolesRequired: Array<String> )
1. 对于没必要区分命名的注解属性，将属性名改为 `value` 以支持无注解属性名的默认属性
2. 添加文档注释说明该注解属性中角色的组合关系为“与”关系还是“或”关系

2024-02-18 07:37 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/RolesRequired.kt
> +        println("[uToken]: $uToken")
不要使用 println，参考 `exception.ExceptionMappers.kt` 使用 `org.jboss.logging.Logger` 类

2024-02-18 07:38 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/model/UTokenCacheData.kt
> +data class UTokenCacheData(
`UtokenCacheData`

2024-02-18 07:38 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/model/db/User.kt
> +    val userRoleBands: List<UserRoleBand>
使用更容易让人能看懂的命名

2024-02-18 07:39 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/model/db/UserRoleBand.kt
> +interface UserRoleBand {
使用更容易让人能看懂的命名

2024-02-18 07:40 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/model/db/Role.kt
> +    val userRoleBands: List<UserRoleBand>
使用更容易让人能看得懂的命名

2024-02-18 07:41 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/AuthResource.kt
这页没格式化

2024-02-18 07:42 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/service/AuthService.kt
> +const val BYTE_SIZE = 8
放到伴生对象里以给它们一个命名空间

2024-02-18 07:43 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/AuthResource.kt
> +        val utokenResult= authService.generateUToken(user.id, input.timestamp)
解构声明变量

2024-02-18 07:45 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/service/AuthService.kt
提交之前记得格式化一下

2024-02-18 07:45 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/service/AuthService.kt
> +    fun generateUToken(id: Long, userTimestamp: Long):Pair<String, Long> {
`generateUtoken`

2024-02-18 07:49 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/service/AuthService.kt
> +        }
这个循环看起来没啥必要，毫秒级的serverTimestamp不太可能重叠

2024-02-18 07:51 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/util/CryptUtil.kt
> +const val FILL_CHARACTER = 'X'
放到伴生对象里，并给予合适的访问权限

2024-02-18 07:53 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/util/CryptUtil.kt
> + * [key]: Long直接 toString 就行了
那你直接重载一个 Long 参数的算了

2024-02-18 07:53 UTC, ArgonarioD commented on src/main/resources/application.yml
> +      "maij-token-policy":
？

2024-02-18 08:31 UTC, ArgonarioD commented on src/test/kotlin/io/github/hammerhfut/rehearsal/AuthResourceTest.kt
> +    val objectMapper = ObjectMapper()
objectMapper要用依赖注入的

2024-02-18 08:32 UTC, ArgonarioD commented on src/test/kotlin/io/github/hammerhfut/rehearsal/AuthResourceTest.kt
不要用 `println`

2024-02-18 08:33 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/AuthResource.kt
> +    }
测试用的接口不要放在 main module 里，放到 test module 里

2024-02-18 08:34 UTC, ArgonarioD requested changes
提交前记得格式化

2024-02-27 06:54 UTC, ArgonarioD requested changes
reviewed

2024-02-27 06:54 UTC, ArgonarioD commented on db/dev/5-schema.sql
把INSERT语句拆分至6-data.sql中

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/RolesRequired.kt
> + *       "data": 123
在 Dokka 中可以使用 markdown 语法

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/RolesRequired.kt
> +                    return true
后续记得删除 或 改至 debug/trace 等级，尽量用
 debug/trace 等级的日志记录 debug 信息

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/interceptor/RolesRequired.kt
> +    }
kotlin class 不能直接反射吗？这个我不太清楚，总之尽量用 kotlin 反射而不是 java 反射。
以及用位置定位参数的健壮性太差，改成用类型或者用注解定位。

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/model/db/RoleGroup.kt
> +    val name: String
`@Key`

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/model/dto/RoleDto.kt
> +)
看起来都可以考虑使用jimmer dto语言

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleGroupResource.kt
> +@Path("/role-group")
用 `/role/group`

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleGroupResource.kt
> +    @Path(("/{id}"))
为什么这么多括号（）

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleResource.kt
> +    }
这个有点没必要，直接在group的接口中全量更新group即可

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleResource.kt
> +    }
不是很懂这个接口是为了什么业务放在这里的

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleResource.kt
> +    fun setUserRole(input: SetUserRoleData) {
Roles

2024-02-27 06:54 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/service/RoleService.kt
> +    }
1. 不要用foreach list来做in，用Set做in判断，如果需要保持加入顺序使用LinkedHashSet。
2. 排序操作在sql中完成，分组操作可以用集合类的groupBy方法。

2024-03-01 05:06 UTC, Prixii commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleResource.kt
> +    }
返回树形role，登录返回的是拍扁之后的，没有更高级的role信息

2024-03-01 16:59 UTC, ArgonarioD commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleResource.kt
> +    }
想起来了，我的

2024-03-03 04:40 UTC, Prixii commented on src/main/kotlin/io/github/hammerhfut/rehearsal/resource/RoleResource.kt
> +    }
不使用全量更新主要是考虑到前端操作的时候，应该很少出现批量移动组的行为，多数还是对单个role进行换组，这样写前端发请求容易点，传输数据也少

2024-03-07 08:15 UTC, merged